<?php

use Magento\Framework\View\Element\Template;
use Project\Blog\ViewModel\Posts;

$postsViewModel = $block->getData('posts_view_model');
$collection = $postsViewModel->getPosts(10);
// var_dump($collection);
// die();
?>
<?php foreach ($collection as $post) : ?>
    <div id="container">
        <div class="product-details">
            <h1><?= $post->getData('title') ?></h1>
            <span class="hint-star star">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star-half-o" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
            </span>


            <!-- The most important information about the product -->
            <!-- <p class="information">"<?= $post->getData('description') ?>"</p> -->



            <!-- 		Control -->
            <div class="control">
                <!-- Start Button buying -->
                <a href="<?php echo $block->getUrl('blog/news/singlepage', ['post_id' => $post->getData('post_id')]); ?>" class="btn">
                    <!-- 		Buy Now / ADD to Cart-->
                    <span class="buy">Read More</span>
                </a>
                <!-- End Button buying -->

            </div>

        </div>

        <!-- 	End	Product details   -->



        <!-- 	Start product image & Information -->

        <div class="product-image">

            <img src="<?= $post->getData('image') ?>" alt="<?= $post->getData('title') ?>">

            <!-- 	product Information-->
            <div class="info">
                <h2>The Description</h2>
                <ul>
                    <li><strong>Author: </strong><?= $post->getData('author') ?></li>
                    <li><strong>Soil Needs: </strong>Damp</li>
                    <li><strong>Zones: </strong>9 - 11</li>
                    <li><strong>Height: </strong>2 - 3 feet</li>
                    <li><strong>Blooms in: </strong>Mid‑Summer - Mid‑Fall</li>
                    <li><strong>Features: </strong>Tolerates heat</li>
                </ul>
            </div>
        </div>
        <!--  End product image  -->
    </div>

<?php endforeach; ?>