<?php

use Magento\Framework\View\Element\Template;
use Project\Blog\ViewModel\Posts;

$postsViewModel = $block->getData('posts_view_model');
$collection = $postsViewModel->getPosts(10);
// var_dump($collection);
// die();
?>
<?php foreach ($collection as $post) : ?>
    <div class="container">
        <div class="card">
            <h2><?= $post->getData('title') ?></h2>
            <img class="" src="<?= $post->getData('image') ?>" alt="<?= $post->getData('image') ?>">
            <p><?= $post->getData('description') ?></p>
            <a href="#">Read More</a>
        </div>
    </div>

<?php endforeach; ?>